# Generated by Django 2.2 on 2020-01-28 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='address',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='name',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='business_id',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='user',
            field=models.ManyToManyField(related_name='user_favorited', to='app.User'),
        ),
    ]
